version: '3.7'

services:

  db:

    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=shade1471
      - POSTGRES_PASSWORD=shade1471
    ports:
      - '5432:5432'